var topics =
[
    [ "adc10_a", "dd/d8d/group__adc10__a__api.html", null ],
    [ "adc12_a", "d1/def/group__adc12__a__api.html", null ],
    [ "aes", "d6/da7/group__aes__api.html", null ],
    [ "battbak", "d7/db0/group__battbak__api.html", null ],
    [ "comp_b", "db/d44/group__comp__b__api.html", null ],
    [ "crc", "dd/d77/group__crc__api.html", null ],
    [ "ctsd16", "da/dff/group__ctsd16__api.html", null ],
    [ "dac12_a", "d2/db7/group__dac12__a__api.html", null ],
    [ "dma", "d4/d5c/group__dma__api.html", null ],
    [ "eusci_a_spi", "d7/d41/group__eusci__a__spi__api.html", null ],
    [ "eusci_a_uart", "d0/d82/group__eusci__a__uart__api.html", null ],
    [ "eusci_b_i2c", "d3/d6e/group__eusci__b__i2c__api.html", null ],
    [ "eusci_b_spi", "d0/d82/group__eusci__b__spi__api.html", null ],
    [ "flashctl", "d1/d38/group__flashctl__api.html", null ],
    [ "gpio", "de/df1/group__gpio__api.html", null ],
    [ "lcd_b", "d5/d67/group__lcd__b__api.html", null ],
    [ "lcd_c", "d8/d53/group__lcd__c__api.html", null ],
    [ "ldopwr", "dd/d7e/group__ldopwr__api.html", null ],
    [ "mpy32", "d1/da2/group__mpy32__api.html", null ],
    [ "oa", "d4/d2f/group__oa__api.html", null ],
    [ "pmap", "d6/db7/group__pmap__api.html", null ],
    [ "pmm", "d6/d02/group__pmm__api.html", null ],
    [ "ram", "dd/d4c/group__ram__api.html", null ],
    [ "ref", "db/d58/group__ref__api.html", null ],
    [ "rtc_a", "d6/dd1/group__rtc__a__api.html", null ],
    [ "rtc_b", "d7/d0e/group__rtc__b__api.html", null ],
    [ "rtc_c", "d3/d6f/group__rtc__c__api.html", null ],
    [ "sd24_b", "d9/d99/group__sd24__b__api.html", null ],
    [ "sfr", "d8/dae/group__sfr__api.html", null ],
    [ "sysctl", "d6/dae/group__sysctl__api.html", null ],
    [ "tec", "d4/dbc/group__tec__api.html", null ],
    [ "timer_a", "d1/d9e/group__timer__a__api.html", null ],
    [ "timer_b", "da/de1/group__timer__b__api.html", null ],
    [ "timer_d", "d7/de4/group__timer__d__api.html", null ],
    [ "tlv", "d0/d1d/group__tlv__api.html", null ],
    [ "ucs", "dd/d9c/group__ucs__api.html", null ],
    [ "usci_a_spi", "da/d4c/group__usci__a__spi__api.html", null ],
    [ "usci_a_uart", "d1/db0/group__usci__a__uart__api.html", null ],
    [ "usci_b_i2c", "d8/de9/group__usci__b__i2c__api.html", null ],
    [ "usci_b_spi", "db/d84/group__usci__b__spi__api.html", null ],
    [ "wdt_a", "d7/d7a/group__wdt__a__api.html", null ],
    [ "Compiler Vorgaben", "d4/d1d/group__compiling__group.html", null ],
    [ "Copyright", "d1/ddc/group___c_o_p_y_r_i_g_h_t___g_r_o_u_p.html", null ]
];